//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.03 at 01:06:50 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.plcopen.org/xml/tc6_0201", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.plcopen.xml.tc6_0201;
