//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.03 at 01:06:50 PM CET 
//


package org.plcopen.xml.tc6_0201;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A generic value
 * 
 * <p>Java class for value complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="value">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="simpleValue">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="arrayValue">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="value">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}value">
 *                           &lt;attribute name="repetitionValue" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="structValue">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="value">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}value">
 *                           &lt;attribute name="member" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "value", propOrder = {
    "simpleValue",
    "arrayValue",
    "structValue"
})
@XmlSeeAlso({
    Value_.ArrayValue.Value.class,
    Value_.StructValue.Value.class
})
public class Value_ {

    protected Value_.SimpleValue simpleValue;
    protected Value_.ArrayValue arrayValue;
    protected Value_.StructValue structValue;

    /**
     * Gets the value of the simpleValue property.
     * 
     * @return
     *     possible object is
     *     {@link Value_.SimpleValue }
     *     
     */
    public Value_.SimpleValue getSimpleValue() {
        return simpleValue;
    }

    /**
     * Sets the value of the simpleValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value_.SimpleValue }
     *     
     */
    public void setSimpleValue(Value_.SimpleValue value) {
        this.simpleValue = value;
    }

    /**
     * Gets the value of the arrayValue property.
     * 
     * @return
     *     possible object is
     *     {@link Value_.ArrayValue }
     *     
     */
    public Value_.ArrayValue getArrayValue() {
        return arrayValue;
    }

    /**
     * Sets the value of the arrayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value_.ArrayValue }
     *     
     */
    public void setArrayValue(Value_.ArrayValue value) {
        this.arrayValue = value;
    }

    /**
     * Gets the value of the structValue property.
     * 
     * @return
     *     possible object is
     *     {@link Value_.StructValue }
     *     
     */
    public Value_.StructValue getStructValue() {
        return structValue;
    }

    /**
     * Sets the value of the structValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value_.StructValue }
     *     
     */
    public void setStructValue(Value_.StructValue value) {
        this.structValue = value;
    }


    /**
     * Array value consisting of a list of occurrances - value pairs
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="value">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}value">
     *                 &lt;attribute name="repetitionValue" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ArrayValue {

        protected List<Value_.ArrayValue.Value> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Value_.ArrayValue.Value }
         * 
         * 
         */
        public List<Value_.ArrayValue.Value> getValue() {
            if (value == null) {
                value = new ArrayList<Value_.ArrayValue.Value>();
            }
            return this.value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}value">
         *       &lt;attribute name="repetitionValue" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Value
            extends Value_
        {

            @XmlAttribute(name = "repetitionValue")
            protected String repetitionValue;

            /**
             * Gets the value of the repetitionValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRepetitionValue() {
                if (repetitionValue == null) {
                    return "1";
                } else {
                    return repetitionValue;
                }
            }

            /**
             * Sets the value of the repetitionValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRepetitionValue(String value) {
                this.repetitionValue = value;
            }

        }

    }


    /**
     * Value that can be represented as a single token string 
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SimpleValue {

        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * Struct value consisting of a list of member - value pairs
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="value">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}value">
     *                 &lt;attribute name="member" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StructValue {

        protected List<Value_.StructValue.Value> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Value_.StructValue.Value }
         * 
         * 
         */
        public List<Value_.StructValue.Value> getValue() {
            if (value == null) {
                value = new ArrayList<Value_.StructValue.Value>();
            }
            return this.value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}value">
         *       &lt;attribute name="member" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Value
            extends Value_
        {

            @XmlAttribute(name = "member", required = true)
            protected String member;

            /**
             * Gets the value of the member property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMember() {
                return member;
            }

            /**
             * Sets the value of the member property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMember(String value) {
                this.member = value;
            }

        }

    }

}
